In [27]:
import polars as pl
import polars.selectors as cs

In [28]:
df_prf = pl.read_csv("./data/anuario_prf.csv")

In [29]:
df_prf.head(10)

shape: (10, 20)
┌──────────────┬────────────┬──────────┬─────┬───┬──────────┬────────────┬────────────┬───────┐
│ data_inversa ┆ dia_semana ┆ horario  ┆ uf  ┆ … ┆ veiculos ┆ latitude   ┆ longitude  ┆ risco │
│ ---          ┆ ---        ┆ ---      ┆ --- ┆   ┆ ---      ┆ ---        ┆ ---        ┆ ---   │
│ str          ┆ str        ┆ str      ┆ str ┆   ┆ i64      ┆ f64        ┆ f64        ┆ str   │
╞══════════════╪════════════╪══════════╪═════╪═══╪══════════╪════════════╪════════════╪═══════╡
│ 2022-01-01   ┆ sábado     ┆ 02:40:00 ┆ PR  ┆ … ┆ 2        ┆ -25.114403 ┆ -48.846755 ┆ alto  │
│ 2022-01-01   ┆ sábado     ┆ 05:22:00 ┆ MS  ┆ … ┆ 3        ┆ -21.228445 ┆ -54.456296 ┆ medio │
│ 2022-01-01   ┆ sábado     ┆ 07:00:00 ┆ RJ  ┆ … ┆ 2        ┆ -23.031498 ┆ -44.177153 ┆ alto  │
│ 2022-01-01   ┆ sábado     ┆ 09:00:00 ┆ MG  ┆ … ┆ 1        ┆ -19.760612 ┆ -44.134754 ┆ baixo │
│ 2022-01-01   ┆ sábado     ┆ 09:00:00 ┆ PB  ┆ … ┆ 2        ┆ -6.964668  ┆ -38.727608 ┆ baixo │
│ 2022-01-01   ┆ sábado     ┆ 10:20:00 ┆ MG  ┆ … ┆ 3        ┆ -19.333821 ┆ -44.361079 ┆ medio │
│ 2022-01-01   ┆ sábado     ┆ 08:05:00 ┆ SC  ┆ … ┆ 3        ┆ -26.650439 ┆ -53.518546 ┆ alto  │
│ 2022-01-01   ┆ sábado     ┆ 12:20:00 ┆ SC  ┆ … ┆ 4        ┆ -27.029823 ┆ -48.60115  ┆ medio │
│ 2022-01-01   ┆ sábado     ┆ 14:15:00 ┆ CE  ┆ … ┆ 5        ┆ -6.741404  ┆ -38.792746 ┆ alto  │
│ 2022-01-01   ┆ sábado     ┆ 09:50:00 ┆ MT  ┆ … ┆ 6        ┆ -15.9106   ┆ -52.2614   ┆ medio │
└──────────────┴────────────┴──────────┴─────┴───┴──────────┴────────────┴────────────┴───────┘

In [30]:
df_prf.schema

Schema([('data_inversa', String),
        ('dia_semana', String),
        ('horario', String),
        ('uf', String),
        ('br', Int64),
        ('km', Int64),
        ('municipio', String),
        ('causa_acidente', String),
        ('tipo_acidente', String),
        ('fase_dia', String),
        ('sentido_via', String),
        ('condicao_metereologica', String),
        ('tipo_pista', String),
        ('tracado_via', String),
        ('uso_solo', String),
        ('pessoas', Int64),
        ('veiculos', Int64),
        ('latitude', Float64),
        ('longitude', Float64),
        ('risco', String)])

In [31]:
TARGET_COL = "risco"

INFERENCE_COL = "causa_acidente"

DROP_COLS = ["municipio", "dia_semana"]
NUMERIC_CLEANUP_COLS = ["km", "latitude", "longitude"]
DATE_TIME_ORIGINALS = ["data_inversa", "horario"]

In [32]:
cond_especial = (
    pl.col("tracado_via").str.contains("Ponte") |
    pl.col("tracado_via").str.contains("Viaduto") |
    pl.col("tracado_via").str.contains("Túnel")
)

cond_aclive_declive = (
    pl.col("tracado_via").str.contains("Aclive") |
    pl.col("tracado_via").str.contains("Declive")
)

In [33]:
df_clean = df_prf.with_columns(
    # pl.col(NUMERIC_CLEANUP_COLS).str.replace_all(",", ".").cast(pl.Float64).fill_null(0.0),
    pl.col("br").cast(pl.Utf8),
    pl.col("data_inversa").str.to_date(format="%Y-%m-%d", strict=False).alias("data"),
    pl.col("horario").str.to_time(format="%H:%M:%S", strict=False).alias("hora_limpa"),
).with_columns(
    pl.col("data").dt.month().alias("mes"),
    pl.col("data").dt.weekday().alias("dia_semana_num"),
    pl.col("hora_limpa").dt.hour().alias("hora"),
).with_columns(
    pl.col("tracado_via")
    .str.split(";")  
    .list.sort()       
    .list.join(";")
    .alias('tracado_via')
).with_columns(
   pl.when(pl.col("tracado_via").str.contains("Reta")).then(pl.lit("Reta"))
      .when(pl.col("tracado_via").str.contains("Curva")).then(pl.lit("Curva"))
      .when(pl.col("tracado_via").str.contains("Interseção")).then(pl.lit("Intersecao"))
      .when(cond_especial).then(pl.lit("Especial"))
      .when(cond_aclive_declive).then(pl.lit("Aclive_Declive"))
      .otherwise(pl.lit("Outro"))
      .alias('tracado_via')
).with_columns(
    cs.string().cast(pl.Categorical).fill_null("Desconhecido"),
    (cs.numeric() - cs.float()).fill_null(0),
)

In [34]:
df_prf.filter((pl.col("latitude").abs() > 90) | (pl.col("longitude").abs() > 180))

shape: (0, 20)
┌──────────────┬────────────┬─────────┬─────┬───┬──────────┬──────────┬───────────┬───────┐
│ data_inversa ┆ dia_semana ┆ horario ┆ uf  ┆ … ┆ veiculos ┆ latitude ┆ longitude ┆ risco │
│ ---          ┆ ---        ┆ ---     ┆ --- ┆   ┆ ---      ┆ ---      ┆ ---       ┆ ---   │
│ str          ┆ str        ┆ str     ┆ str ┆   ┆ i64      ┆ f64      ┆ f64       ┆ str   │
╞══════════════╪════════════╪═════════╪═════╪═══╪══════════╪══════════╪═══════════╪═══════╡
└──────────────┴────────────┴─────────┴─────┴───┴──────────┴──────────┴───────────┴───────┘

In [35]:
cols_to_drop_final = DROP_COLS + DATE_TIME_ORIGINALS + ["hora_limpa", "hora"]

In [36]:
df_final = df_clean.drop(cols_to_drop_final)

In [37]:
df_final

shape: (258_737, 19)
┌─────┬─────┬─────┬────────────────────────────────┬───┬───────┬────────────┬─────┬────────────────┐
│ uf  ┆ br  ┆ km  ┆ causa_acidente                 ┆ … ┆ risco ┆ data       ┆ mes ┆ dia_semana_num │
│ --- ┆ --- ┆ --- ┆ ---                            ┆   ┆ ---   ┆ ---        ┆ --- ┆ ---            │
│ cat ┆ cat ┆ i64 ┆ cat                            ┆   ┆ cat   ┆ date       ┆ i8  ┆ i8             │
╞═════╪═════╪═════╪════════════════════════════════╪═══╪═══════╪════════════╪═════╪════════════════╡
│ PR  ┆ 116 ┆ 33  ┆ Ingestão de álcool pelo        ┆ … ┆ alto  ┆ 2022-01-01 ┆ 1   ┆ 6              │
│     ┆     ┆     ┆ condut…                        ┆   ┆       ┆            ┆     ┆                │
│ MS  ┆ 163 ┆ 393 ┆ Condutor deixou de manter      ┆ … ┆ medio ┆ 2022-01-01 ┆ 1   ┆ 6              │
│     ┆     ┆     ┆ dist…                          ┆   ┆       ┆            ┆     ┆                │
│ RJ  ┆ 101 ┆ 457 ┆ Reação tardia ou ineficiente   ┆ … ┆ alto  ┆ 2022-01-01 ┆ 1   ┆ 6              │
│     ┆     ┆     ┆ d…                             ┆   ┆       ┆            ┆     ┆                │
│ MG  ┆ 40  ┆ 508 ┆ Acumulo de água sobre o        ┆ … ┆ baixo ┆ 2022-01-01 ┆ 1   ┆ 6              │
│     ┆     ┆     ┆ pavime…                        ┆   ┆       ┆            ┆     ┆                │
│ PB  ┆ 116 ┆ 8   ┆ Mal súbito do condutor         ┆ … ┆ baixo ┆ 2022-01-01 ┆ 1   ┆ 6              │
│ …   ┆ …   ┆ …   ┆ …                              ┆ … ┆ …     ┆ …          ┆ …   ┆ …              │
│ SC  ┆ 282 ┆ 302 ┆ Velocidade Incompatível        ┆ … ┆ medio ┆ 2025-09-27 ┆ 9   ┆ 6              │
│ SP  ┆ 381 ┆ 82  ┆ Ausência de reação do condutor ┆ … ┆ medio ┆ 2025-08-30 ┆ 8   ┆ 6              │
│ RJ  ┆ 493 ┆ 20  ┆ Ausência de reação do condutor ┆ … ┆ medio ┆ 2025-08-25 ┆ 8   ┆ 1              │
│ SC  ┆ 101 ┆ 321 ┆ Condutor deixou de manter      ┆ … ┆ medio ┆ 2025-09-28 ┆ 9   ┆ 7              │
│     ┆     ┆     ┆ dist…                          ┆   ┆       ┆            ┆     ┆                │
│ AL  ┆ 316 ┆ 189 ┆ Ingestão de álcool pelo        ┆ … ┆ alto  ┆ 2025-08-30 ┆ 8   ┆ 6              │
│     ┆     ┆     ┆ condut…                        ┆   ┆       ┆            ┆     ┆                │
└─────┴─────┴─────┴────────────────────────────────┴───┴───────┴────────────┴─────┴────────────────┘

In [38]:
df_final["risco"].value_counts()

shape: (3, 2)
┌───────┬────────┐
│ risco ┆ count  │
│ ---   ┆ ---    │
│ cat   ┆ u32    │
╞═══════╪════════╡
│ baixo ┆ 42432  │
│ alto  ┆ 73277  │
│ medio ┆ 143028 │
└───────┴────────┘

In [39]:
df_final.write_parquet("./data/anuario_prf.parquet")